import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
public class PacientesLista extends JFrame{
    public PacientesLista() {
        JFrame frame = new JFrame("Paciente");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 1000);
        JPanel panel = new JPanel(new GridLayout(27,2));
        JLabel datos = new JLabel();
        Border border = BorderFactory.createLineBorder(Color.getHSBColor((float)0.1,(float)0.6,(float)0.6),3);
        datos.setBorder(border);
        datos.setSize(750,50);
        datos.setText("Datos personales");
        JLabel vacio = new JLabel();
        vacio.setSize(10, 50);
        JTextField text = new JTextField();
        text.setSize(300, 50);
        JTextField text2 = new JTextField();
        text2.setSize(300, 50);
        JLabel nombre = new JLabel();
        nombre.setText("Nombre");
        nombre.setSize(300, 50);
        JLabel apellidos = new JLabel();
        apellidos.setText("Apellidos");
        apellidos.setSize(300, 50);
        JTextField text3 = new JTextField();
        text3.setSize(300, 50);
        JComboBox<String> list1 = new JComboBox<>();
        list1.addItem("Seleccione su genero");
        list1.addItem("Masuculino");
        list1.addItem("Femenino");
        list1.addItem("Prefiero no decirlo");
        list1.setSize(500, 50);
        JLabel direccion = new JLabel();
        direccion.setText("Domicilio");
        direccion.setSize(300, 50);
        JLabel genero = new JLabel();
        genero.setText("Genero");
        genero.setSize(300, 50);
        JTextField text4 = new JTextField();
        text4.setSize(200, 50);
        JLabel nac = new JLabel();
        nac.setText("Fecha de nacimiento");
        nac.setSize(300, 50);
        JTextField text5 = new JTextField();
        text5.setSize(200, 50);
        JLabel ocupacion = new JLabel();
        ocupacion.setText("Ocupacion");
        ocupacion.setSize(300, 50);
        JTextField text6 = new JTextField();
        text6.setSize(100, 50);
        JLabel estciv = new JLabel();
        estciv.setText("Estado civil");
        JPanel panel2 = new JPanel(new GridLayout(1,2));
        JPanel panel3 = new JPanel(new GridLayout(1,2));
        JTextField text7 = new JTextField();
        text7.setSize(300, 50);
        JLabel tel = new JLabel();
        tel.setText("Telefono");
        tel.setSize(300, 50);
        JTextField texto8 = new JTextField();
        texto8.setSize(300, 50);
        JLabel celec = new JLabel();
        celec.setText("Correo Electronico");
        JLabel infomed = new JLabel();
        infomed.setBorder(border);
        infomed.setSize(400,50);
        infomed.setText("Informacion medica");
        JLabel infoseg = new JLabel();
        infoseg.setBorder(border);
        infoseg.setSize(400,50);
        infoseg.setText("Informacion seguro medico");
        JTextField text9 = new JTextField();
        text9.setSize(300, 50);
        JLabel motivo = new JLabel();
        motivo.setText("Motivo de consulta");
        motivo.setSize(300, 50);
        JTextField text10 = new JTextField();
        text10.setSize(300, 50);
        JLabel seguro = new JLabel();
        seguro.setText("Nombre del Seguro");
        seguro.setSize(300, 50);
        JTextField text11 = new JTextField();
        text11.setSize(300, 50);
        JLabel antecedentes = new JLabel();
        antecedentes.setSize(300, 50);
        antecedentes.setText("Antecedentes Medicos Relevantes");
        JTextField text12 = new JTextField();
        text12.setSize(300, 50);
        JLabel poliza = new JLabel();
        poliza.setText("Numero dePoliza");
        poliza.setSize(300, 50);
        JTextField texto13 = new JTextField();
        texto13.setSize(300, 50);
        JLabel medic = new JLabel();
        medic.setSize(300, 50);
        medic.setText("Medicamentos Actuales");
        JTextField text14 = new JTextField();
        text14.setSize(300, 50);
        JLabel titular = new JLabel();
        titular.setSize(300, 50);
        titular.setText("Nombre del Titular de la Poliza");
        JTextField text15 = new JTextField();
        text15.setSize(300, 50);
        JLabel alergias = new JLabel();
        alergias.setText("Alergias");
        JLabel vacio2 = new JLabel();
        vacio2.setSize(300, 50);
        JLabel vacio3 = new JLabel();
        vacio3.setSize(300, 50);
        JLabel vacio4 = new JLabel();
        vacio4.setSize(10, 50);
        JLabel contacto = new JLabel();
        contacto.setBorder(border);
        contacto.setSize(400,50);
        contacto.setText("Contacto de Emergencia");
        JTextField text16 = new JTextField();
        text16.setSize(300, 50);
        JLabel nombre2 = new JLabel();
        nombre2.setText("Nombre Completo");
        JLabel vacio5 = new JLabel();
        vacio5.setSize(10, 50);
        JLabel vacio6 = new JLabel();
        vacio6.setSize(10, 50);
        JTextField text17 = new JTextField();
        text17.setSize(300, 50);
        JLabel tel2 = new JLabel();
        tel2.setText("Telefono");
        JTextField text18 = new JTextField();
        text18.setSize(300, 50);
        JLabel relacion = new JLabel();
        relacion.setText("Relacion con Paciente");
        relacion.setSize(300, 50);
        JLabel vacio7 = new JLabel();
        vacio7.setSize(10, 50);
        JLabel consentimiento = new JLabel();
        consentimiento.setBorder(border);
        consentimiento.setSize(400,50);
        consentimiento.setText("Consentimiento del Paciente");
        JCheckBox check = new JCheckBox();
        check.setSize(10, 50);
        check.setText("Autorizo el Tratamiento para mi Condicion");
        JLabel vacio8 = new JLabel();
        vacio8.setSize(10, 50);
        JLabel paciente = new JLabel();
        paciente.setText("Nombre y Firma del Paciente");
        paciente.setSize(300, 50);
        JLabel fecha = new JLabel();
        fecha.setText("Fecha");
        fecha.setSize(300, 50);
        JLabel vacio9 = new JLabel();
        vacio9.setSize(10, 50);
        JPanel panel4 = new JPanel(new GridLayout(1,2));
        JButton button = new JButton();
        JLabel vacio10 = new JLabel();
        vacio10.setSize(10, 50);
        button.setSize(50, 50);
        button.setText("Confirmar");
        panel2.add(text5);
        panel2.add(text6);
        panel3.add(ocupacion);
        panel3.add(estciv);
        panel4.add(vacio10);
        panel4.add(button);
        panel.add(vacio);
        panel.add(datos);
        panel.add(text);
        panel.add(text2);
        panel.add(nombre);
        panel.add(apellidos);
        panel.add(text3);
        panel.add(list1);
        panel.add(direccion);
        panel.add(genero);
        panel.add(text4);
        panel.add(panel2);
        panel.add(nac);
        panel.add(panel3);
        panel.add(text7);
        panel.add(texto8);
        panel.add(tel);
        panel.add(celec);
        panel.add(infomed);
        panel.add(infoseg);
        panel.add(text9);
        panel.add(text10);
        panel.add(motivo);
        panel.add(motivo);
        panel.add(seguro);
        panel.add(text11);
        panel.add(text12);
        panel.add(antecedentes);
        panel.add(poliza);
        panel.add(texto13);
        panel.add(text14);
        panel.add(medic);
        panel.add(titular);
        panel.add(text15);
        panel.add(vacio2);
        panel.add(alergias);
        panel.add(vacio3);
        panel.add(vacio4);
        panel.add(contacto);
        panel.add(text16);
        panel.add(vacio5);
        panel.add(nombre2);
        panel.add(vacio6);
        panel.add(text17);
        panel.add(text18);
        panel.add(tel2);
        panel.add(relacion);
        panel.add(vacio7);
        panel.add(consentimiento);
        panel.add(check);
        panel.add(vacio8);
        panel.add(paciente);
        panel.add(fecha);
        panel.add(vacio9);
        panel.add(panel4);
        frame.add(panel);
        frame.setVisible(true);
    }
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new PacientesLista());
    }
}